service: serverless-tennis-bot
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-central-1
  logRetentionInDays: 5  # Set retention to 5 days
  environment:
    TENNIS_TELEGRAM_BOT_CHAT_ID: ${ssm:/tennis/TENNIS_TELEGRAM_BOT_CHAT_ID}
    TENNIS_TELEGRAM_BOT_TOKEN: ${ssm:/tennis/TENNIS_TELEGRAM_BOT_TOKEN}
    SCRIPTS_DB_URL: ${ssm:/tennis/SCRIPTS_DB_URL}

functions:
  scheduledFootballFunction:
    handler: handler.scheduledFunction
    timeout: 520
    events:
      - schedule:
          rate: cron(0/5 * ? * * *)
          enabled: true
          input:
            parameter: FOOTBALL
  scheduledFunction:
    handler: handler.scheduledFunction
    timeout: 520
    events:
      - schedule:
          rate: cron(0/5 * ? * * *)
          enabled: true
          input:
            parameter: TENNIS
  morningFootballFunction:
    handler: handler.morningFunction
    timeout: 520
    events:
      - schedule:
          rate: cron(30 5 * * ? *)
          enabled: true
          input:
            parameter: FOOTBALL
  morningFunction:
    handler: handler.morningFunction
    timeout: 520
    events:
      - schedule:
          rate: cron(30 5 * * ? *)
          enabled: true
          input:
            parameter: TENNIS
plugins:
  - serverless-plugin-typescript
  - serverless-plugin-log-retention  # Include the plugin